### ISSUE TITLE
You can use AdSupport with iOS 6+

### ISSUE THREAD

**Issue by larryaasen** [deniza/app_tracking_transparency#1]
This line will work in iOS 6+ so you don't need to wrap it in `#available(iOS 14, *)`:

https://github.com/deniza/app_tracking_transparency/blob/73ff395ca3170251fba638899a7bd1b2d57808bb/ios/Classes/SwiftAppTrackingTransparencyPlugin.swift#L80

See reference from Apple:
https://developer.apple.com/documentation/adsupport/asidentifiermanager/1614151-advertisingidentifier

**Comment by deniza** [comment]
@larryaasen thanks for the correction. I published a fixed version to pub. (1.0.1)
