### ISSUE TITLE
IDFA dialog not working on real devices

### ISSUE THREAD

**Issue by nathan1658** [deniza/app_tracking_transparency#11]
Hi all, the prompt is working fine on simulator, however it doesn't shown on real device.

I tried to submit to App Store Connect and I got rejected with following message:
'_We're looking forward to completing the review of your app, but we need more information to continue. Specifically, we noticed that your app uses the AppTrackingTransparency framework, but we haven't been able to locate the App Tracking Transparency permission request._'

No error shown on xcode console, any Idea on how to fix this? Thanks!

**Comment by nathan1658** [comment]
Found a discussion on apple developer forum, seems related to iOS14.3.. ( mine is too)
[https://developer.apple.com/forums/thread/671623]

**Comment by stonekase** [comment]
This is correct, this library doesnt work.
