### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by giorgio-borghetto** [deniza/app_tracking_transparency#16]
Good morning,

Once I build into Flutter, I receive this error:

Command CompileSwift failed with a nonzero exit code
    /Users/borghettogi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/app_tracking_transparency-1.1.0+1/ios/Classes/SwiftAppTrackingTransparencyPlugin.swift:3:8: error: no such module 'AppTrackingTransparencyPlugin'
    import AppTrackingTransparencyPlugin

**Comment by untp** [comment]
Can you please try the latest version of this package? (`app_tracking_transparency: ^2.0.0`)

**Comment by giorgio-borghetto** [comment]
I've upgraded to the latest version, but the error is the same:

 /Users/borghettogi/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/app_tracking_transparency-2.0.0+1/ios/Classes/SwiftAppTrackingTransparencyPlugin.swift:3:8: error: no such module 'AppTrackingTransparency'
    import AppTrackingTransparency

**Comment by nektar95** [comment]
same error, xcode version 12.5

**Comment by 111110100** [comment]
Fixed mine by making sure the platform line in my Podfile is '9.0'. Also added  AppTransparency.framework Frameworks, Libraries, and Embedded Content under Targets/Runner/General.

**Comment by Mapk26** [comment]
I had the same problem with iOS versions 12.5

Fixed with solution found on stackoverflow:
https://stackoverflow.com/questions/64472144/ios-13-library-not-loaded-apptrackingtransparency-framework-apptrackingtransp

I didnt need to embed content, keeping it as "Do Not Embed"
