### ISSUE TITLE
Tap popup when running an integration test

### ISSUE THREAD

**Issue by ryujignh** [deniza/app_tracking_transparency#18]
Hello there. Is there a way to tap either the "Allow" or "Ask App Not to Track" button on the popup when testing Flutter integration?

**Comment by deniza** [comment]
FlutterDriver can be used to test both Flutter and native iOS UI components inside a Flutter application. To interact with the native iOS UI components, you can use the driver.requestData method to send data to the native side and driver.waitFor method to wait for the results.
