### ISSUE TITLE
How soon can I ask for ATT permission again if user denied?

### ISSUE THREAD

**Issue by danieeelfc** [deniza/app_tracking_transparency#19]
How soon can I ask for ATT permission again if user denied?

I tried to push the calendar 6 months later, but I still could not ask for ATT permission once more.

As far as I've tested, the only scenario that could be asked again is if the user uninstalls the app and installs again later.

**Comment by deniza** [comment]
As far as I know you can not ask again if user once denied to give permission. You can try to show permission dialog by calling AppTrackingTransparency.requestTrackingAuthorization() but nothing going to happen if user once denied. If you want to test it multiple times, you can change the Bundle Identifier temporally.

**Comment by danilofuchs** [comment]
You cannot ask again, but you can link them to your app's page on the settings app

**Comment by RalphBergmannKMB** [comment]
You are not allowed to ask again. I did it with a real iOS app and it was rejected by Apple. If the user declines, you have to accept it.
