### ISSUE TITLE
Suggestion: User Messaging Platform

### ISSUE THREAD

**Issue by mamm26** [deniza/app_tracking_transparency#2]
Hello, first of all thank you very much for this package. I wanted to suggest if there is a possibility to implement the User Messaging Platform to this package, it would be quite useful and it is appreciated.

iOS: https://developers.google.com/admob/ump/ios/quick-start
Android: https://developers.google.com/admob/ump/android/quick-start

Regards.

**Comment by Gimu** [comment]
@mamm26 You can try out [https://github.com/Gimu/admob_consent](https://github.com/Gimu/admob_consent) for a UMP wrapper, I recently updated it from the old google consent SDK.

I came across this repository as the official UMP implementation still has issues with the ATT explainer and dialog not showing up (UMP should automatically trigger the ATT dialog according to the docs), there are multiple [discussions](https://groups.google.com/g/google-admob-ads-sdk/c/lY3wFek6910) on Google's SDK forum. So I'd probably wait for Google to fix/enable that first.

**Comment by deniza** [comment]
@mamm26 I want to keep this package as simple as possible. @Gimu 's wrapper seems to fit your requirements as soon as Google fixes ATT issue.
