### ISSUE TITLE
Module not found on iOS

### ISSUE THREAD

**Issue by pptavozl** [deniza/app_tracking_transparency#20]
Hello, I'm getting the next error when i tried to build my app 

Anyone had the same error?

`
Running pod install...                                            488.1s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         5.6s
Xcode build done.                                           58.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/usrs/development/Flutter/esssss/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'app_tracking_transparency' not found
    @import app_tracking_transparency;
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete`

**Comment by luis-cruzt** [comment]
same here

**Comment by EliseiNicolae** [comment]
Looks like `flutter pub repiar cache` is not workign anymore...

<img width="789" alt="image" src="https://github.com/deniza/app_tracking_transparency/assets/43387542/72fef8ec-29da-4792-8d0b-d5d2ebe2f4e2">
