### ISSUE TITLE
ATT Not Working on IOS 15.1

### ISSUE THREAD

**Issue by zoozobib** [deniza/app_tracking_transparency#23]
We have got a message from app store.

"We're looking forward to completing our review, but we need more information to continue. Your app uses the AppTrackingTransparency framework, but we are unable to locate the App Tracking Transparency permission request when reviewed on iOS 15.1."

**Comment by SinoMiles** [comment]
same issue. I think we need to find a new plug.

**Comment by SinoMiles** [comment]
same issue

**Comment by saigkl** [comment]
same issue

**Comment by deniza** [comment]
Do you have any chance to test it on your own device running ios 15.1? I can not find a problem when testing in my test devices. 

Do your app use remote or local notifications, I mean, do you also request notification permission on app launch?

**Comment by SinoMiles** [comment]
@deniza I have tested it on my iPhone 12 ios 15.1.1, didn't show the dialog
I don't use notifications . Look at the link below. I have changed the swift code.it works now.
https://github.com/deniza/app_tracking_transparency/issues/22#issuecomment-958761305

**Comment by deniza** [comment]
I just tested the example coming with app_tracking_transparency package on my ios 15.1 device (iPhone 11). Everything seems working fine. The only difference between the code you [mentioned](https://github.com/deniza/app_tracking_transparency/issues/22#issuecomment-958761305) and our implementation is that our implementation first checks the tracking status by calling AppTrackingTransparency.trackingAuthorizationStatus and if it is notDetermined then shows the dialog. This is the only way if we want to show a custom explainer dialog before the official tracking dialog. (Google recommends this approach btw.) If you do not want to show a custom explainer dialog then its fine to call AppTrackingTransparency.requestTrackingAuthorization directly after app launch. Apple's official documentation also recommends checking tracking status first as stated [here](https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager/3547037-requesttrackingauthorization)

Could you please run the example code that comes with the package on your own test device?

**Comment by barisozbey** [comment]
> Do you have any chance to test it on your own device running ios 15.1? I can not find a problem when testing in my test devices.
> 
> Do your app use remote or local notifications, I mean, do you also request notification permission on app launch?

@deniza I'm requesting notification permission and ATT on app launch? Im requesting notification first? And i got exactly same answer from apple. Do you have any idea about that?

**Comment by deniza** [comment]
@barisozbey You could use a delayed call, ie Future.delayed(Duration(seconds: 1), () { request ATT here   }), or show a custom explainer dialog first, like in example.

**Comment by zoozobib** [comment]
> @barisozbey You could use a delayed call, ie Future.delayed(Duration(seconds: 1), () { request ATT here }), or show a custom explainer dialog first, like in example.

thanks , it is working

**Comment by usaikoo** [comment]
It working when you place the ATT request code in home page after splash or main page. Do not call directly in main page, as for me, I place the ATT request code in my home page after main page is called, then splash page is called again after this, my home page is called with custom pop up ATT request alert.

**Comment by h4h13** [comment]
@deniza Is this solution can be applied for iOS 15.3


Anyone facing ATT is not working on iOS 15.3

**Comment by h4h13** [comment]
@deniza Correct me if I'm wrong, we have moved the ATT request from app launch to button click and it's still not showing in the prod builds and app store is rejecting because of that. 

At the movement we can't add explainer dialog because of product requirement

**Comment by Touchunit** [comment]
> @deniza Is this solution can be applied for iOS 15.3
> 
> Anyone facing ATT is not working on iOS 15.3

yes same issue
