### ISSUE TITLE
Dialog shown when not requested

### ISSUE THREAD

**Issue by ecorradini** [deniza/app_tracking_transparency#25]
I'm having an issue calling `requestTrackingAuthorization()`.
I've created a page for privacy consent. After tapping a "continue" button, the following code is executed to show the popup:

```
if(Platform.isIOS) {
    final status = await AppTrackingTransparency.requestTrackingAuthorization();
    if(status == TrackingStatus.authorized) {
      PrivacyManager.allowTracking();
    }
    else {
      PrivacyManager.notAllowTracking();
    }
  }
```

However, the popup is always shown when app is starting, not when requested.

**Comment by deniza** [comment]
AppTrackingTransparency.requestTrackingAuthorization() shows native tracking request dialog. You should check AppTrackingTransparency.trackingAuthorizationStatus if you want to know user's choice. Please consult the usage example on pub.dev for a basic workflow.
