### ISSUE TITLE
Apple does not like showing custom message before showing native dialog and have ability to defer the decision

### ISSUE THREAD

**Issue by aquadesk** [deniza/app_tracking_transparency#27]
Just FYI,

I got this reject message from apple.

So we should always show the dialog regardless of the decision.

--------

Hello,

Thank you for your resubmission. Upon further review, we identified an additional issue that needs your attention. See below for more information.

If you have any questions, we are here to help. Reply to this message in App Store Connect and let us know.

Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage

We noticed your app includes App Tracking Transparency permissions requests, but it encourages or directs users to accept tracking. Specifically, your app directs the user to accept tracking in the following way(s): 

- A message appears before the permission request, and the user can close the message and delay the permission request with the “decide later” button. The user should always proceed to the permission request after the message.

Permission requests give users control of their personal information. It is important to respect their decision about how their data is used.

Next Steps

To resolve this issue, please revise the permission request process in your app so that the user is not inappropriately encouraged or directed to accept tracking.

If necessary, you may provide more information about why you are requesting permission to track before the request appears. If the user is trying to use a feature in your app that won't function without tracking, you may include a notification to inform the user and provide a link to the Settings app.

**Comment by untp** [comment]
Thanks for reporting this. I checked now, Google updated their guide.
(https://support.google.com/admob/answer/10115027?hl=en) They suggest a custom dialog with only a Continue button.

![v7GokkrtuxKhV5lYTjfANyoi3Q3O1UlDTQBV.png](https://user-images.githubusercontent.com/54450843/163704377-3d41ad96-1c50-449b-925d-698a66808c13.png)

**Comment by aquadesk** [comment]
Thanks for following up.
This makes sense!

Thanks for the awesome project!

**Comment by deniza** [comment]
@aquadesk thanks for the update on this.
@untp thanks for fast reaction.

And updated version is just published.
