### ISSUE TITLE
Rework plateform checking

### ISSUE THREAD

**Issue by EArminjon2** [deniza/app_tracking_transparency#30]
Flutter doc suggest to use Platform.iOS inside views and defaultTargetPlatform for API.
This allow use to override defaultTargetPlatform on unit test and manage Platform through context inside widget testing.

```dart
// Change this
Platform.isIOS

// To this
defaultTargetPlatform == TargetPlatform.iOS
```

https://api.flutter.dev/flutter/foundation/defaultTargetPlatform.html

**Comment by deniza** [comment]
merged. thanks for the contribution :)
