### ISSUE TITLE
Changes in AdMob & AdSense program policies

### ISSUE THREAD

**Issue by palicka** [deniza/app_tracking_transparency#33]
Apparently there are changes in admob program policies: [AdMob & AdSense program policies
Troubleshooting TCF v2.0 implementation](https://support.google.com/admob/answer/9999955)

And I started to see error 3.3 (error codes are in the link above) in my admob console for iOS app:

> 3.3: The TC string last updated date was more than 13 months ago. CMP should delete the old TC string and reobtain consent.
I really don't know if I should do something or wait for the SDKs to be updated. Could you please have a look at it ?
Thank you

**Comment by deniza** [comment]
This should not be related to ATT requests. As far as I know, you can only get one IDFA string per user per app install.
