### ISSUE TITLE
Invoke the dialog a second time to change the tracking choice

### ISSUE THREAD

**Issue by robman70** [deniza/app_tracking_transparency#41]
I can't invoke the dialog a second time to change the tracking choice.
I would like to make the dialog visible again, without forcing the user to go into the app settings.
How can I do?

**Comment by deniza** [comment]
In iOS, once the user has made their decision on whether to allow or deny app tracking, the app tracking authorization dialog cannot be shown again for that specific app. The user can still change their decision from the Settings app, but the app cannot request authorization again.
