### ISSUE TITLE
Privacy manifest file for iOS is missing

### ISSUE THREAD

**Issue by oremlawi** [deniza/app_tracking_transparency#51]
To ensure a smooth app update and avoid App Store rejection, kindly consider adding a privacy manifest to your library. This helps developers reflect data collection practices in our own manifests.

[Apple documentation.](https://developer.apple.com/support/third-party-SDK-requirements/)

**Comment by samir-a-ts** [comment]
Any progress on this one? The deadline is week.  @deniza

**Comment by bazmichal** [comment]
There is a prepared opened pull request for this https://github.com/deniza/app_tracking_transparency/pull/49. 
Btw, is there a sense of adding privacy.xconfig file for the plugin, if it doesn't track anything and moreover, isn't listed by apple? 

https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by deniza** [comment]
Thanks for reporting this issue. We are calling a function that retrieves device's advertising identifier. So technically we are collecting some kind of deviceId data. The thing is; if you are using this library, you probably also use a package to display ads such as google_mobile_ads. Every ads framework out there use advertising identifier to track devices. Long story short: your final app bundle will include a PrivacyInfo.xcprivacy file that fulfills the requirements anyway. At least, that's how I understand it.

**Comment by bazmichal** [comment]
@deniza some applications do not necessarily have ad. libraries implemented. Integration of the analytics/marketing providers, like for example Adjust or facebook_app_events will require having your library `app_tracking_transparency` by Apple itself. So I think it will be anyway to merge the PR and make sure your only and unique package helps community. 

We apreaciate your support!

**Comment by deniza** [comment]
On a second thought, calling an api to request IDFA  is not a necessity for the main purpose of this library. There are other packages accomplishing this. Maybe its the right time to remove this function from the package and create a blank PrivacyPolicy file as suggested. What do you think? @bazmichal

**Comment by bazmichal** [comment]
@deniza I think that there are still a lot of developers using it specifically for this purpose and additionally, some of them are not aware of Privacy manifests yet, so there will be definitely more people seeking for that in advance while trying to push their apps into the App Store. 

Obviously its yours decision, but in case you would like to remove this, I would personally ensure a smooth transition documentation for users, since anyway, your package is the main player in terms of IDFA and tracking.

**Comment by deniza** [comment]
Library update to 2.0.5 fixes privacy policy issue for Apple. Thanks to everyone for the contributions. 🚀
