### ISSUE TITLE
When an APP must display ATT modal?

### ISSUE THREAD

**Issue by h3nr1ke** [deniza/app_tracking_transparency#52]
Hello all,

I have an application that does not show ads, but we want to promote this app using the ad campaigns.

Our partner asked us about the ATT and SKAdNetwork implementation inside our app, but right now we do not do that.

The only tracking we have is google analytics for internal usage, not sharing with ad networks.

My question is, if I dont have ad inside the app, should I add ATT just to promote my app using ads?

I know that this is not an issue about the module, but like me, someone else maybe is with the exactly same doubts and we can improve the README with this information =)

Thanks for the help =)

**Comment by deniza** [comment]
Hi,

In summary, if your app or any client-side SDK/library within your app requires access to the IDFA (Identifier for Advertisers), you need to request App Tracking Transparency (ATT) permission. Without this permission, the default IDFA will be all zeroes and will not be usable for tracking the user or device.

**Comment by h3nr1ke** [comment]
Hey @deniza , thanks a lot to asnwer that.

That is clear now... =) 

Thanks for this great plugin =)
