### ISSUE TITLE
unable to locate the App Tracking Transparency permission request when reviewed on iOS 17.5.

### ISSUE THREAD

**Issue by lunasoft79** [deniza/app_tracking_transparency#54]
Guideline 2.1 - Information Needed

We're looking forward to completing our review, but we need more information to continue. Your app uses the AppTrackingTransparency framework, but we are unable to locate the App Tracking Transparency permission request when reviewed on iOS 17.5.

Next Steps

Please explain where we can find the App Tracking Transparency permission request in your app. The request should appear before any data is collected that could be used to track the user.

If you've implemented App Tracking Transparency but the permission request is not appearing on devices running the latest operating system, please review the [available documentation](https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager/3547037-requesttrackingauthorization) and confirm App Tracking Transparency has been correctly implemented.

If your app does not track users, update your [app privacy information in App Store Connect](https://help.apple.com/app-store-connect/#/dev1b4647c5b) to not declare tracking. You must have the [Account Holder or Admin role](https://developer.apple.com/support/roles/) to update app privacy information.

Resources 

- Tracking is linking data collected from your app with third-party data for advertising purposes, or sharing the collected data with a data broker. Learn more about [tracking](https://developer.apple.com/app-store/app-privacy-details/#user-tracking). 
- See Frequently Asked Questions about the [requirements for apps that track users](https://developer.apple.com/app-store/user-privacy-and-data-use/#permission-to-track).
- Review developer documentation for [App Tracking Transparency](https://developer.apple.com/documentation/apptrackingtransparency).

**Comment by JuKu** [comment]
Same issue here.

**Comment by Mikhail-Ivanou** [comment]
@deniza  Could you help? As PR https://github.com/deniza/app_tracking_transparency/pull/55 is not accepted, what can be solution?
