### ISSUE TITLE
Apple Review won't accept my app because the app tracking transparency dialog doesn't appear (iOS 17)

### ISSUE THREAD

**Issue by JuKu** [deniza/app_tracking_transparency#56]
Hi there,

I have a problem with the App Store Review process.
They said, that in my app (which uses this plugin for this purpose) there isn't an app tracking transparency framework implemented / detected. They ask, when the dialog appears. But normally the dialog should appear on the first startup.

My code:
```
Future<void> main() async {
  WidgetsFlutterBinding
      .ensureInitialized();

  // Request for App Tracking Transparency
  final TrackingStatus trackingStatus = await AppTrackingTransparency.trackingAuthorizationStatus;
  developer.log('tracking status: ${trackingStatus.toString()}', name: 'app_tracking_transparency');
  
  if (trackingStatus == TrackingStatus.notDetermined || trackingStatus == TrackingStatus.denied) {
    // show app tracking transparency dialog after the first frame
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      developer.log('show dialog', name: 'app_tracking_transparency');
      await AppTrackingTransparency.requestTrackingAuthorization();
    });
  }

  // ...

}
```

Does anyone has an idea, why the dialog doesn't appear?
Does this relates to https://github.com/deniza/app_tracking_transparency/issues/54 or is this another issue?

**Comment by deniza** [comment]
Hi. The issue should be resolved in the latest release. Please update your plugin to version 2.0.6 and try again. 

Thank you.

**Comment by JuKu** [comment]
@deniza I've tried this and updatet to version 2.0.6 .
But apple is still criticizing it.

**Comment by Mikhail-Ivanou** [comment]
I've got reject from Apple too. 
My device works ok, but tester's one - she see no permission request (unfortunately I have no access to that device)

**Comment by takeapps88** [comment]
@deniza 

I also updated the version to 2.0.6, but it was rejected during Apple's review.

It was reviewed on iOS 17.6, and they mentioned that the popup appears on the iPhone but not on the iPad. Indeed, when I checked on my own devices, the popup appears on the iPhone, but it does not appear on the iPad.

**Comment by JuKu** [comment]
Should we create a new issue for this or re-open this one?

**Comment by SahidKhan89** [comment]
@JuKu i've created a new issue #57 

Are others still having issues with this or know of a good workaround for the time being?

**Comment by Mikhail-Ivanou** [comment]
After 2 weeks struggling with Apple, could pass with other library only. Permissions handler helped, or just other device, that has no issues with app tracking transparency permission :)

**Comment by SahidKhan89** [comment]
thanks @Mikhail-Ivanou, is this the flutter package https://pub.dev/packages/permission_handler you ended up using instead to get Apple to approve your submission? I'll give that a go.

**Comment by Mikhail-Ivanou** [comment]
> thanks @Mikhail-Ivanou, is this the flutter package https://pub.dev/packages/permission_handler you ended up using instead to get Apple to approve your submission? I'll give that a go.

yep
Don't forget to modify podfile

**Comment by deniza** [comment]
Hi everyone, the permission_handler package offers more functionality than the app_tracking_transparency plugin, but for tracking purposes, it essentially performs the same task. I recommend running the example code provided with the plugin in a sample project and testing it on both the simulator and an actual test device to ensure it's working correctly

**Comment by Mikhail-Ivanou** [comment]
[app_tracking_transparency](https://github.com/deniza/app_tracking_transparency) is great package that helped us much.
Now there are smth strange. It works correctly in my device and simulator. And my QA reports that she see permission request in one device, but cannot see in other. Actually I had no more ideas and time, as I should release app in July (so I had a delay already)

**Comment by JuKu** [comment]
> > thanks @Mikhail-Ivanou, is this the flutter package https://pub.dev/packages/permission_handler you ended up using instead to get Apple to approve your submission? I'll give that a go.
> 
> yep Don't forget to modify podfile

Can anyone please provide a little piece of example code for the app tracking transparency?

**Comment by JuKu** [comment]
Okay, I get it.
I didn't know that the app tracking transparency is only a permission and not an overall framework (as you might expect from the name).

So here is a little piece of code for all the others with the same problem:
```
Future<void> requestTrackingPermission() async {
  var logger = Logger();

  // Prüfe, ob die Berechtigung bereits gewährt wurde
  var status = await Permission.appTrackingTransparency.status;

  logger.i("request for app tracking transparency permission");

  if (status != PermissionStatus.granted) {
    // Fordere die Berechtigung an
    status = await Permission.appTrackingTransparency.request();

    if (status == PermissionStatus.granted) {
      logger.i("tracking permission granted");
    } else {
      logger.i("tracking permission not granted");
    }
  } else {
    logger.i("tracking permission already granted");
  }
}
```

**Comment by JuKu** [comment]
The workaround doesn't work.
Is the library already fixed?
